image: golang:1.18.1

variables:
  # Please edit to your GitLab project
  REPO_NAME: github.com/abo/influx-proxy
  VERSION: "1.0.0"
  BUILD_OPTS: ""

before_script:
  - GOPROXY=https://proxy.golang.com.cn,direct go get -v -t -d ./...

stages:
  - test
  - build

unit_tests:
  stage: test
  script:
    - go test -v ./... -coverprofile .testCoverage.txt

compile:
  stage: build
  script:
    - GOARCH=amd64 GOOS=darwin go build $BUILD_OPTS -ldflags="-X main.Version=$VERSION -X main.Commit=$CI_COMMIT_SHORT_SHA" -o $CI_PROJECT_DIR/influxp-darwin-amd64-$CI_COMMIT_SHORT_SHA ./cmd/influxp/
    - GOARCH=amd64 GOOS=linux go build $BUILD_OPTS -ldflags="-X main.Version=$VERSION -X main.Commit=$CI_COMMIT_SHORT_SHA" -o $CI_PROJECT_DIR/influxp-linux-amd64-$CI_COMMIT_SHORT_SHA ./cmd/influxp/
    - GOARCH=arm64 GOOS=linux go build $BUILD_OPTS -ldflags="-X main.Version=$VERSION -X main.Commit=$CI_COMMIT_SHORT_SHA" -o $CI_PROJECT_DIR/influxp-linux-arm64-$CI_COMMIT_SHORT_SHA ./cmd/influxp/
    - mkdir etc && cp ./cmd/influxp/*.yml etc/ && cp -r ./cmd/influxp/init.d etc/
  artifacts:
    name: "influxproxy-V$VERSION-$CI_COMMIT_SHORT_SHA"
    paths:
      - $CI_PROJECT_DIR/influxp-darwin-amd64-$CI_COMMIT_SHORT_SHA
      - $CI_PROJECT_DIR/influxp-linux-amd64-$CI_COMMIT_SHORT_SHA
      - $CI_PROJECT_DIR/influxp-linux-arm64-$CI_COMMIT_SHORT_SHA
      - etc

    
