proxy:
  bind-addr: ":8086" # 监听地址和端口
  https-cert: "" # https 证书, 例如 "/etc/influxp/tls.cert"
  https-cert-key: "" # https 证书 key, 例如 "/etc/influxp/tls.key"
  username: "" # 认证用户名, 在访问管理接口及查询/写入接口时需要认证
  password: "" # 认证密码, 在访问管理接口及查询/写入接口时需要认证
  data-dir: "influxpdata" # 数据存储目录, 包括元数据与 buffer, 确保有权限读写
  measurements: # 纳管的 Measurement 范围
    - cpe.*
  # flush-size: 10000 # 高级配置
  # flush-time: 1
  # flush-pool-size: 20
  # rewrite-interval: 10
  # node-check-interval: 1  # 高级配置: check node is active or not
  # node-write-timeout: 10  # 高级配置: timeout when write to node
  # idle-timeout: 10 

sharding: # 各 Measurement 的分片 Tag
  - name: "cpe.cpe_lw_conn_rttploss"
    tag: "customer"
  - name: "cpe.cpe_lw_conn_rxtx"
    tag: "customer"

cluster: # 集群配置
  local-id: 1
  peers:
    - id: 1
      url: "http://127.0.0.1:8086"

data-nodes: # 初次启动时使用的 influxdb 节点, 后续运行时动态增加不再使用这个配置
  - url: "http://127.0.0.1:8087"
    username: ""
    password: ""
  - url: "http://127.0.0.1:8088"
    username: ""
    password: ""

logging:
    level: "INFO" #logs at or above this threshold go to stderr, DEBUG/INFO/WARN/ERROR
    file: "/var/log/influxp.log" #If non-empty, use this log file, otherwise log to console
    file-max-size: 128 #Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited.
    file-max-age: 15 #Defines the maximum number of days to retain old log files. if empty, old log files is never deleting.
    # write-tracing: true
    # query-tracing: true

