#!/bin/bash
### BEGIN INIT INFO
# Provides:          influxp
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: LightWAN Influx Proxy
# Description:       LightWAN Influx Proxy
### END INIT INFO

dir="/home/influxp"
cmd="${dir}/influxp --config=${dir}/config.yml"
user=""

name=`basename $0`
pid_file="/var/run/$name.pid"
stdout_log="/var/log/$name.log"
stderr_log="/var/log/$name.err"

get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && ps -p `get_pid` > /dev/null 2>&1
}

case "$1" in
    bootstrap)
    if is_running; then
        echo "Unable to bootstrap, $name is running [`get_pid`]"
        exit 1
    else
        cmd="${cmd} -bootstrap -dir=${dir}"
        if $cmd; then
            echo "Bootstrapped, save to ${dir}"
        else
            echo "Unable to bootstrap"
        fi
    fi
    ;;
    provision)
    if is_running; then
        echo "Unable to provision, $name is running [`get_pid`]"
        exit 1
    else
        cmd="${cmd} -provision -dir=${dir}"
        if $cmd; then
            echo "Provisioned, load from ${dir}"
        else
            echo "Unable to provision"
        fi
    fi
    ;;
    start)
    if is_running; then
        echo "Already started [`get_pid`]"
    else
        echo "Starting $name"
        cd "$dir"
        if [ -z "$user" ]; then
            $cmd >> "$stdout_log" 2>> "$stderr_log" &
        else
            sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
        fi
        echo $! > "$pid_file"
        if ! is_running; then
            echo "Unable to start, see $stdout_log and $stderr_log"
            exit 1
        else 
            echo "Started [`get_pid`]"
        fi
    fi
    ;;
    stop)
    if is_running; then
        echo -n "Stopping $name [`get_pid`].."
        kill `get_pid`
        for i in 1 2 3 4 5 6 7 8 9 10
        # for i in `seq 10`
        do
            if ! is_running; then
                break
            fi

            echo -n "."
            sleep 1
        done
        echo

        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
            if [ -f "$pid_file" ]; then
                rm "$pid_file"
            fi
        fi
    else
        echo "Not running"
    fi
    ;;
    restart)
    $0 stop
    if is_running; then
        echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if is_running; then
        echo "Running [`get_pid`]"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {bootstrap|provision|start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0